### ISSUE TITLE
Multiple lists with searchboxes throws an error trying to focus

### ISSUE THREAD

**Issue by fdlane** [knoxville-utilities-board/ember-nrg-ui#129]
https://github.com/knoxville-utilities-board/ember-nrg-ui/blob/6df84b20aca87c1bd846dea36713f6b2bdfe34dd/addon/components/nrg-list/header/search/component.js#L46

**Comment by zachnthebox** [comment]
Can you create a example we can test against?

**Comment by fdlane** [comment]
Assertion Failed: Registering two shortcuts with the same path: [Focus Search Box] and [Focus Search Box]
Ember error

**Comment by zachnthebox** [comment]
Ah, It's a keyboard shortcuts issue. Would you like an option to turn off the "search shortcut" when you want to have multiple lists?
