### ISSUE TITLE
Context menu mixin page is broken

### ISSUE THREAD

**Issue by TSenter** [knoxville-utilities-board/ember-nrg-ui#260]
Since #256 was merged, the [context menu mixin page](https://knoxville-utilities-board.github.io/ember-nrg-ui/#/view-mixins/context-menu) is basically useless because there is no authenticated user.

A fix would be to set the `disabled` property in the [context menu service](https://github.com/knoxville-utilities-board/ember-nrg-ui/blob/master/addon/context-menu/service.js#L15) to `false` on initialization of the route or application, and to set it back to true when the `willTransition` action is fired.

**Comment by zachnthebox** [comment]
It think it might be better to have this default to true, and have our internal library to set this to false when appropriate. The feature should work by default.
