### ISSUE TITLE
Sidebar footer issue on smaller screens

### ISSUE THREAD

**Issue by fdlane** [knoxville-utilities-board/ember-nrg-ui#512]
The footer is not pinned to the bottom when the sidebar is opened on a smaller screen.

![image](https://github.com/knoxville-utilities-board/ember-nrg-ui/assets/735646/06575f77-e815-4b93-aa9e-8013ef03ec29)

<img width="250" alt="image" src="https://github.com/knoxville-utilities-board/ember-nrg-ui/assets/735646/06f50708-5cb2-4d86-bf8b-4ebca8b6f225">

**Comment by KeithClinard** [comment]
<img width="302" alt="image" src="https://github.com/knoxville-utilities-board/ember-nrg-ui/assets/2756533/5b80a479-48d0-43ed-9721-f4f103468bff">

**Comment by TSenter** [comment]
Fixed by #573, #575
