### ISSUE TITLE
Unwrap parent sidebar menu item && add variable tagname

### ISSUE THREAD

**Issue by KeithClinard** [knoxville-utilities-board/ember-nrg-ui#62]
https://github.com/knoxville-utilities-board/ember-nrg-ui/blob/master/addon/components/nrg-sidebar-menu/template.hbs#L5-L7

Should be unwrapped from `link-to`, and should be able to specify `div` tagName and `clickable parent-route` class

**Comment by zachnthebox** [comment]
Taken care of in PR
